baseurl: ''
url: 'https://turbodieseldecolombiagd.com'
name: 'Turbo Diesel de Colombia GD'
title: 'Turbo Diesel de Colombia GD'
author: Cristobal - T.D.G.D.
facebook: https://www.facebook.com/profile.php?id=100064895403683
maps: "https://maps.app.goo.gl/aDvF3ppBjMRaGK2y5"
telefono: "3132751889"
whatsapp: 3506329106
direccion:  "Carrera 82a #8C - 45, Bogotá"
email: ventas@turbodieseldecolombiagd.com

markdown: kramdown

permalink: :slug/

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  servicios:
    output: true
    permalink: /servicios/:path/
  posts:
    output: true
    permalink: /blog/:categories/:slug/
  redirects:
    output: true